#!/bin/bash

# Formatting constants
export BOLD=`tput bold`
export UNDERLINE_ON=`tput smul`
export UNDERLINE_OFF=`tput rmul`
export TEXT_BLACK=`tput setaf 0`
export TEXT_RED=`tput setaf 1`
export TEXT_GREEN=`tput setaf 2`
export TEXT_YELLOW=`tput setaf 3`
export TEXT_BLUE=`tput setaf 4`
export TEXT_MAGENTA=`tput setaf 5`
export TEXT_CYAN=`tput setaf 6`
export TEXT_WHITE=`tput setaf 7`
export BACKGROUND_BLACK=`tput setab 0`
export BACKGROUND_RED=`tput setab 1`
export BACKGROUND_GREEN=`tput setab 2`
export BACKGROUND_YELLOW=`tput setab 3`
export BACKGROUND_BLUE=`tput setab 4`
export BACKGROUND_MAGENTA=`tput setab 5`
export BACKGROUND_CYAN=`tput setab 6`
export BACKGROUND_WHITE=`tput setab 7`
export RESET_FORMATTING=`tput sgr0`

# Wrapper function for Maven's mvn command.
mvn-color() {
	# Filter mvn output using sed
	mvn $@ | sed -e "s/\(\[INFO\]\ \-.*\)/${RESET_FORMATTING}\1/g" \
	-e "s/\(\[INFO\] \[.*\)/${RESET_FORMATTING}${BOLD}\1${RESET_FORMATTING}/g" \
	-e "s/\[INFO\] \(--- .* ---\)/\[INFO\] ${BOLD}${TEXT_MAGENTA}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[INFO\].*SUCCESS \[.*\]\)/${BOLD}${TEXT_GREEN}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[INFO\].*FAILURE \[.*\]\)/${BOLD}${TEXT_RED}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[INFO\].*SKIPPED\)/${BOLD}${TEXT_BLACK}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[INFO\] BUILD SUCCESS.*\)/${BOLD}${TEXT_GREEN}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[INFO\] BUILD FAILURE.*\)/${BOLD}${TEXT_RED}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[WARNING\].*\)/${BOLD}${TEXT_YELLOW}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[ERROR\].*\)/${BOLD}${TEXT_RED}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[debug\].*\)/${TEXT_YELLOW}\1${RESET_FORMATTING}/g" \
	-e "s/\(\[DEBUG\].*\)/${TEXT_YELLOW}\1${RESET_FORMATTING}/g" \
	-e "s/\(Download.*\)/${BOLD}${TEXT_CYAN}\1${RESET_FORMATTING}/g" \
	-e "s/Tests run: \(0\),/${BOLD}${TEXT_YELLOW}Tests run: \1${RESET_FORMATTING},/g" \
	-e "s/Tests run: \([1-9][0-9]*\),/${BOLD}${TEXT_GREEN}Tests run: \1${RESET_FORMATTING},/g" \
	-e "s/Failures: \([1-9][0-9]*\),/${BOLD}${TEXT_RED}Failures: \1${RESET_FORMATTING},/g" \
	-e "s/Errors: \([1-9][0-9]*\),/${BOLD}${TEXT_RED}Errors: \1${RESET_FORMATTING},/g" \
	-e "s/Skipped: \([1-9][0-9]*\)/${BOLD}${TEXT_YELLOW}Skipped: \1${RESET_FORMATTING}/g" \
	-e "s/\(<<< FAILURE!.*\)/${BOLD}${TEXT_RED}\1${RESET_FORMATTING}/g"
	
	# Make sure formatting is reset
	echo -ne ${RESET_FORMATTING}
}
